train_hyperparams:
  batch_size: 1               # possibly effective batch=16 via accumulation
  epochs: 12
  lr: 5e-5
  optimizer: AdamW
  weight_decay: 1e-4
  scheduler:
    type: cosine              # or linear warmup+decay
    warmup_steps: 1000

clip:
  model_name: "openai/clip-vit-base-patch32"

models:
  MultiModalClassifier:
    embed_dim: 512
    num_classes: 2
    num_heads: 8
    num_layers: 3
    hidden_dim: 256